-- ===========================================================================
-- Organon Studio - esquema inicial
--
-- Cuatro capas: corpus (quien escribio que), semantica (que significa cada
-- termino para cada autor), logica (como se reconstruye el argumento) y
-- dialectica (quien discute con quien).
--
-- El esquema lo posee Flyway; Hibernate corre en ddl-auto=validate.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- CAPA 1 - CORPUS FILOSOFICO
-- ---------------------------------------------------------------------------

CREATE TABLE philosopher (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(160) NOT NULL,
    epoch                 VARCHAR(20)  NOT NULL,
    school                VARCHAR(160),
    biographical_summary  TEXT,
    created_at            TIMESTAMPTZ  NOT NULL,
    updated_at            TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_philosopher_name UNIQUE (name),
    CONSTRAINT ck_philosopher_epoch CHECK (
        epoch IN ('ANTIGUA', 'MEDIEVAL', 'MODERNA', 'CONTEMPORANEA')
    )
);

CREATE TABLE work (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    philosopher_id         BIGINT       NOT NULL,
    title                  VARCHAR(240) NOT NULL,
    original_year          INTEGER,
    philosophical_problem  TEXT,
    core_thesis            TEXT,
    direct_adversary_id    BIGINT,
    created_at             TIMESTAMPTZ  NOT NULL,
    updated_at             TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_work_philosopher FOREIGN KEY (philosopher_id)
        REFERENCES philosopher (id) ON DELETE CASCADE,
    CONSTRAINT fk_work_adversary FOREIGN KEY (direct_adversary_id)
        REFERENCES work (id) ON DELETE SET NULL,
    CONSTRAINT ck_work_not_self_adversary
        CHECK (direct_adversary_id IS NULL OR direct_adversary_id <> id)
);

CREATE INDEX idx_work_philosopher ON work (philosopher_id);
CREATE INDEX idx_work_adversary   ON work (direct_adversary_id);

CREATE TABLE passage (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id       BIGINT       NOT NULL,
    locator       VARCHAR(120) NOT NULL,
    text_content  TEXT         NOT NULL,
    page_number   INTEGER,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_passage_work FOREIGN KEY (work_id)
        REFERENCES work (id) ON DELETE CASCADE,
    CONSTRAINT ck_passage_page CHECK (page_number IS NULL OR page_number >= 0)
);

CREATE INDEX idx_passage_work ON passage (work_id);
CREATE UNIQUE INDEX uk_passage_work_locator ON passage (work_id, locator);


-- ---------------------------------------------------------------------------
-- CAPA 2 - SEMANTICA (sobrecarga de terminos)
-- ---------------------------------------------------------------------------

CREATE TABLE semantic_concept (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term         VARCHAR(120) NOT NULL,
    description  TEXT,
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_semantic_concept_term UNIQUE (term)
);

CREATE TABLE term_definition (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concept_id             BIGINT      NOT NULL,
    philosopher_id         BIGINT      NOT NULL,
    work_id                BIGINT,
    operational_definition TEXT        NOT NULL,
    notes                  TEXT,
    created_at             TIMESTAMPTZ NOT NULL,
    updated_at             TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_term_definition_concept FOREIGN KEY (concept_id)
        REFERENCES semantic_concept (id) ON DELETE CASCADE,
    CONSTRAINT fk_term_definition_philosopher FOREIGN KEY (philosopher_id)
        REFERENCES philosopher (id) ON DELETE CASCADE,
    CONSTRAINT fk_term_definition_work FOREIGN KEY (work_id)
        REFERENCES work (id) ON DELETE CASCADE,
    CONSTRAINT uk_term_definition_scope
        UNIQUE NULLS NOT DISTINCT (concept_id, philosopher_id, work_id)
);

CREATE INDEX idx_term_definition_concept     ON term_definition (concept_id);
CREATE INDEX idx_term_definition_philosopher ON term_definition (philosopher_id);
CREATE INDEX idx_term_definition_work        ON term_definition (work_id);


-- ---------------------------------------------------------------------------
-- CAPA 3 - RECONSTRUCCION LOGICA
-- ---------------------------------------------------------------------------

CREATE TABLE argument (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id              BIGINT       NOT NULL,
    passage_id           BIGINT,
    name                 VARCHAR(240) NOT NULL,
    formal_scheme        VARCHAR(40)  NOT NULL,
    latex_formalization  TEXT,
    sound_status         VARCHAR(20)  NOT NULL,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_argument_work FOREIGN KEY (work_id)
        REFERENCES work (id) ON DELETE CASCADE,
    CONSTRAINT fk_argument_passage FOREIGN KEY (passage_id)
        REFERENCES passage (id) ON DELETE SET NULL,
    CONSTRAINT ck_argument_scheme CHECK (
        formal_scheme IN ('MODUS_PONENS', 'MODUS_TOLLENS', 'SILOGISMO_CATEGORICO',
                          'SILOGISMO_DISYUNTIVO', 'SILOGISMO_HIPOTETICO',
                          'REDUCTIO_AD_ABSURDUM', 'INDUCTIVE', 'ABDUCTIVE',
                          'TRASCENDENTAL', 'ANALOGICO', 'NO_CLASIFICADO')
    ),
    CONSTRAINT ck_argument_sound_status CHECK (
        sound_status IN ('PENDIENTE', 'SOLIDO', 'FALAZ')
    )
);

CREATE INDEX idx_argument_work    ON argument (work_id);
CREATE INDEX idx_argument_passage ON argument (passage_id);
CREATE INDEX idx_argument_status  ON argument (sound_status);

CREATE TABLE premise (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    argument_id   BIGINT      NOT NULL,
    order_index   INTEGER     NOT NULL,
    statement     TEXT        NOT NULL,
    is_enthymeme  BOOLEAN     NOT NULL DEFAULT FALSE,
    premise_type  VARCHAR(30) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_premise_argument FOREIGN KEY (argument_id)
        REFERENCES argument (id) ON DELETE CASCADE,
    CONSTRAINT uk_premise_order UNIQUE (argument_id, order_index),
    CONSTRAINT ck_premise_order_index CHECK (order_index >= 0),
    CONSTRAINT ck_premise_type CHECK (
        premise_type IN ('AXIOMATICA', 'EMPIRICA', 'DEFINICION',
                         'INFERENCIA_INTERMEDIA', 'CONCLUSION')
    )
);

CREATE INDEX idx_premise_argument  ON premise (argument_id);
CREATE INDEX idx_premise_enthymeme ON premise (argument_id) WHERE is_enthymeme;

CREATE TABLE objection (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premise_id      BIGINT      NOT NULL,
    objection_type  VARCHAR(40) NOT NULL,
    explanation     TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_objection_premise FOREIGN KEY (premise_id)
        REFERENCES premise (id) ON DELETE CASCADE,
    CONSTRAINT ck_objection_type CHECK (
        objection_type IN ('CONTRAEJEMPLO', 'FALACIA_FORMAL', 'PETICION_DE_PRINCIPIO',
                           'REDEFINICION', 'REGRESO_AL_INFINITO', 'FALSA_DICOTOMIA',
                           'AMBIGUEDAD', 'GENERALIZACION_APRESURADA')
    )
);

CREATE INDEX idx_objection_premise ON objection (premise_id);


-- ---------------------------------------------------------------------------
-- CAPA 4 - RED DIALECTICA
-- ---------------------------------------------------------------------------

CREATE TABLE dialectical_relation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_argument_id  BIGINT      NOT NULL,
    target_argument_id  BIGINT      NOT NULL,
    relation_type       VARCHAR(20) NOT NULL,
    description         TEXT,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_dialectical_source FOREIGN KEY (source_argument_id)
        REFERENCES argument (id) ON DELETE CASCADE,
    CONSTRAINT fk_dialectical_target FOREIGN KEY (target_argument_id)
        REFERENCES argument (id) ON DELETE CASCADE,
    CONSTRAINT uk_dialectical_relation_triple
        UNIQUE (source_argument_id, target_argument_id, relation_type),
    CONSTRAINT ck_dialectical_no_self_loop
        CHECK (source_argument_id <> target_argument_id),
    CONSTRAINT ck_dialectical_relation_type CHECK (
        relation_type IN ('REFUTA', 'PRESUPONE', 'EXTIENDE', 'RADICALIZA', 'MATIZA')
    )
);

CREATE INDEX idx_dialectical_source ON dialectical_relation (source_argument_id);
CREATE INDEX idx_dialectical_target ON dialectical_relation (target_argument_id);


-- ---------------------------------------------------------------------------
-- Documentacion de las decisiones no obvias del esquema
-- ---------------------------------------------------------------------------

COMMENT ON CONSTRAINT uk_term_definition_scope ON term_definition IS
    'NULLS NOT DISTINCT (PostgreSQL 15+) impide dos definiciones generales del mismo termino para el mismo autor: con work_id NULL solo cabe una.';

COMMENT ON CONSTRAINT fk_work_adversary ON work IS
    'SET NULL en vez de CASCADE: perder la obra contraria no debe borrar la obra que polemizaba con ella.';

COMMENT ON CONSTRAINT fk_argument_passage ON argument IS
    'SET NULL: si se borra el pasaje, el argumento sobrevive desanclado de la cita.';

COMMENT ON CONSTRAINT ck_dialectical_no_self_loop ON dialectical_relation IS
    'Un argumento no se relaciona consigo mismo: eso seria contradiccion interna, no dialectica entre posiciones.';

COMMENT ON COLUMN premise.is_enthymeme IS
    'Supuesto implicito: premisa que el autor no escribio pero que su inferencia necesita.';

COMMENT ON COLUMN passage.locator IS
    'Referencia canonica academica (AT VII 40, KrV B 4, Metafisica 980a), no pagina de una edicion concreta.';
