-- ===========================================================================
-- Repaso socratico
--
-- Cada vez que el lector se pone a prueba con una idea queda un intento: la
-- pregunta que le hizo el asistente, lo que respondio y como salio. El
-- historial decide que repasar despues (lo nunca visto primero, lo flojo
-- luego) y viaja en la copia de seguridad.
-- ===========================================================================

CREATE TABLE review_attempt (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    argument_id         BIGINT      NOT NULL,
    challenge_kind      VARCHAR(20) NOT NULL,
    question            TEXT        NOT NULL,
    counterexample      TEXT,
    hint                TEXT,
    answer              TEXT,
    rating              VARCHAR(20),
    what_worked         TEXT,
    what_to_improve     TEXT,
    follow_up_question  TEXT,
    answered_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_review_attempt_argument FOREIGN KEY (argument_id)
        REFERENCES argument (id) ON DELETE CASCADE,
    CONSTRAINT ck_review_attempt_kind CHECK (challenge_kind IN ('SUPUESTO', 'CONTRAEJEMPLO')),
    CONSTRAINT ck_review_attempt_rating CHECK (rating IS NULL OR rating IN ('SOLIDA', 'A_MEDIAS', 'FLOJA')),
    CONSTRAINT ck_review_attempt_answer CHECK ((answer IS NULL) = (answered_at IS NULL)),
    CONSTRAINT ck_review_attempt_rated CHECK (rating IS NULL OR answered_at IS NOT NULL)
);

CREATE INDEX idx_review_attempt_argument ON review_attempt (argument_id, answered_at DESC);

COMMENT ON COLUMN review_attempt.rating IS
    'Solidez del razonamiento del lector, no si coincide con el autor. Una valoracion que el modelo devuelva mal escrita se guarda como A_MEDIAS.';

COMMENT ON COLUMN review_attempt.challenge_kind IS
    'SUPUESTO: pregunta por un supuesto implicito de la idea. CONTRAEJEMPLO: la idea no tiene supuestos marcados y el desafio es un caso que la pone en aprietos.';
